import { Aoty } from "@/models/album";

const allTimeFaves: Aoty[] = [
  ["Kate Bush - Aerial", "1WgKjmhHM2NEkxEaoeJwb1"],
  ["Kate Bush - Hounds of Love", "5G5UwqPsxDKpxJLX4xsyuh"],
  ["Talking Heads - Speaking In Tongues", "78MM8HrabEGPLVWaJkM2t1"],
  ["Talking Heads - Remain in Light", "1JvXxLsm0PxlGH4LXzqMGq"],
  ["Talk Talk - Spirit of Eden", "4YXo7p7aubyVIbNLoVlBp9"],
  ["Weyes Blood - Titanic Rising", "0Cuqhgy8vm96JEkBY3polk"],
  ["Destroyer - Poison Season", "5xFvYKTDT4D7LvdPwUoltJ"],
  ["Destroyer - Kaputt", "3yy32elu0ZXO6xq2bTuhmU"],
  ["Oneohtrix Point Never - R Plus Seven", "0p7nH5bz0pWBor10osUBuD"],
  ["Oneohtrix Point Never - Replica", "4Wq9kfnBR0npGfsuQl8kDW"],
  ["Jon Hopkins - Immunity", "0Dg1KwgmtUzeMQonDCUFhQ"],
  ["The Avalanches - Since I Left You", "0YtYaaO0aipyeQl0xhAWTO"],
  ["Bruce Springsteen - Born In The U.S.A.", "0PMasrHdpaoIRuHuhHp72O"],
  ["Pink Floyd - The Wall", "5Dbax7G8SWrP9xyzkOvy2F"],
  ["Pink Floyd - Wish You Were Here", "0bCAjiUamIFqKJsekOYuRw"],
  ["Julia Holter - Loud City Song", "3JhMmVL9ISUnRaVbrJ72OB"],
  ["King Crimson - In The Court Of The Crimson King", "75ol9OP8bJaRqzGimpFHDm"],
  ["Fleetwood Mac - Rumours", "1bt6q2SruMsBtcerNVtpZB"],
  ["Michael Jackson - Thriller", "2ANVost0y2y52ema1E9xAZ"],
  ["Steve Reich - Music For 18 Musicians", "2zUpKJnQgl3YMUJ4dqYo61"],
  ["The Strokes - Room On Fire", "3HFbH1loOUbqCyPsLuHLLh"],
  ["The Strokes - Is This It", "2yNaksHgeMQM9Quse463b5"],
  ["Tame Impala - Currents", "79dL7FLiJFOO0EoehUHQBv"],
  ["Beach House - Depression Cherry", "5tTmosmyV33wCiwniZc4Qs"],
  ["Beach House - Bloom", "0AL7olZ75pi55q9p1eHaD8"],
  ["case/lang/veirs - case/lang/veirs", "0U5U4AU94YjYY2QoOpmwfN"],
  ["Animal Collective - Merriweather Post Pavillion", "6BRq5g6CWiFgN3NrjLGAYq"],
  ["GAS - Pop", "32Nl49izVyngH22kD1lrkk"],
  [
    "Spiritualized - Ladies and gentlemen we are floating in space",
    "56YzQ0dhmRMDryZsrjdHun",
  ],
  ["J Dilla - Donuts", "5fMlysqhFE0itGn4KezMBW"],
  ["Aphex Twin - Richard D. James Album", "77Lae5VorRCNpgZFMW8yRO"],
  ["Aphex Twin - Selected Ambient Works 85-92", "7aNclGRxTysfh6z0d8671k"],
  ["Radiohead - In Rainbows", "5vkqYmiPBYLaalcmjujWxK"],
  ["Radiohad - Kid A", "6GjwtEZcfenmOf6l18N7T7"],
  ["Bill Evans - Undercurrent", "3b2s2A8DPISbaQNxhrEsGQ"],
  [
    "Max Richter - Recomposed by Max Richter: Vivaldi, The Four Seasons",
    "5yuG2LEkf7QA9ZGIXldCmy",
  ],
  ["Kendrick Lamar - To Pimp A Butterfly", "7ycBtnsMtyVbbwTfJwRjSP"],
  ["New Order - Power Corruption and Lies", "6NTrwu1XJ56jBPx7HMksbZ"],
  ["Tears For Fears - Songs From The Big Chair", "7y7459SFZReE5Wec4hejv5"],
  ["Brian Eno - Ambient 2: The Plateaux Of Mirror", "5ma9r5NFV0poevmydI2qgO"],
  ["Madvillain - Madvillainy", "19bQiwEKhXUBJWY6oV3KZk"],
  ["Squarepusher - Hard Normal Daddy", "08XR1KLcDo49Yay08q7CsE"],
  ["Oval - 94diskont.", "33xUwaoTPJ9aNbCJZEpRol"],
  ["Disasterpeace - FEZ (Original Game Soundtrack)", "0UzcBQ0p8f4byXmGo3MMa6"],
  ["My Bloody Valentine - Loveless", "3USQKOw0se5pBNEndu82Rb"],
  ["deadmau5 - Random Album Title", "78djcfLlGna8lO1XwgdSIg"],
  ["Low - Double Negative", "0fWKkkVCj14CllpjPLjU9P"],
  ["Fiona Apple - Fetch The Bolt Cutters", "0fO1KemWL2uCCQmM22iKlj"],
  ["Fiona Apple - The Idler Wheel", "6B5favhKTShFTjRLsKIUfa"],
  ["Miles Davis - Brew", "3Q0zkOZEOC855ErOOJ1AdO"],
];

export const ALL_TIME_FAVES = allTimeFaves.map((e) => e[1]);
