import { Aoty, AotyList } from "@/models/album";

const aotys2023: Aoty[] = [
  [
    "Caroline Polachek - Desire, I Want To Turn Into You",
    "22PkV1Le9P3X4RY4xtmK0q",
  ],
  ["Susanne Sundfor - blomi", "0Cq0t6HFg2UeAEqwED7ezE"],
  ["Sufjan Stevens - Javelin", "2KqSL3vLfyVO7rrZJL9tUs"],
  ["Fennesz - Senzatempo", "23S2QUtp39zI02mGkMMblu"],
  ["Olivia Rodrigo - Guts", "1xJHno7SmdVtZAtXbdbDZp"],
  ["Black Country, New Road - Live at Bush Hall", "1w7YBHqXz6UfLrVur8JAcW"],
  ["Sampha - Lahai", "5GuWww4OaildzkmTTlfMN3"],
  ["boygenius - the record", "0e9GjrztzBw8oMC6n2CDeI"],
  ["Indigo De Souza - All Of This Will End", "15eosxhQvPKQ1g0tfrnAt2"],
  ["yeule - softscars", "7t01lwQRDjtEvwiAm88ACH"],
  ["Squid - O Monolith", "6El4L0QbF7grZlJmpv7KPI"],
  ["Julie Byrne - The Greater Wings", "1KeJzjoh4vHrJif6BsYKRg"],
  ["Jess Williamson - Time Ain't Accidental", "1hh0GMMCLN9hYcLtOSWxTZ"],
  ["Jessie Ware - That! Feels Good!", "17g3sAeWfpHSJlqMHuRAr6"],
  [
    "The Chemical Brothers - For That Beautiful Feeling",
    "5cLkbqs0qo552lJvXH1JTH",
  ],
  ["King Krule - Space Heavy", "36tUlc8fGxaUTv4cLmC9UJ"],
  ["billy woods, Kenny Segal - Maps", "3VoX4iyvy7et6Qt47e2XwS"],
  [
    "Kara Jackson - Why Does The Earth Give Us People To Love?",
    "2itoipNg0XOD1uwThhkVtO",
  ],
  ["Monsieur Perine - Bolero Apocaliptico", "6TLARwYU6FpUDAA3nxtKM0"],
  ["Sofia Kourtesis - Madres", "6zt8N56kz8b58cnHnBhx9f"],
  ["PJ Harvey - I Inside The Old Year Dying", "2ik9ifrDdzxRsJU9fy9TFc"],
  ["Mitski - The Land Is Inhospitable And So Are We", "2Cn1d2KgbkAqbZCJ1RzdkA"],
  ["feeble little horse - Girl with Fish", "4lVMhVIgEdxIoTu7gS7CoT"],
  ["L'Rain - I Killed Your Dog", "0POQzFrAUw7qplp8HwXsHP"],
  ["Lonnie Holley - Oh Me Oh My", "1jXTqjpWJXAd2PtGcnp8pe"],
  ["Avalon Emerson - & the Charm", "6gRl7N6UQKKmXCv3nhYlMu"],
  ["The Lemon Twigs - Everything Harmony", "5X0MAnUVN7eEZyO1LjprIk"],
  ["Thy Slaughter - Soft Rock", "5lgqJ8vLfDGbL1AFHgj2o1"],
  ["Joanna Sternberg - I've Got Me", "3l3xPtGZXUcnQaNlpbjvR0"],
  ["Kin Leonn - mirror in the gleam", "3Z9EDLs1ThHsqM2nXwRxkA"],
  ["Yo La Tengo - This Stupid World", "3LaJpJFSY3cmLFEHJl2z6E"],
  ["Arooj Aftab - Love in Exile", "0nP1MzWoPnLfLglLS0v4CQ"],
  ["Skrillex - Quest for Fire", "7tWP3OG5dWphctKg4NMACt"],
  [
    "James Holden - Imagine This Is A High Dimensional Space of All Possibilities",
    "4c04wXoadgnqqrxeDUCnFP",
  ],
  ["100 gecs - 10,000 gecs", "2XS5McKf3zdJWpcZ4OkZPZ"],
  ["Tinashe - BB/ANG3L", "0Ytzeqoskd5VfSVfGGA1SM"],
  ["PinkPantheress - Heaven knows", "2pOEFqvfxp5uUQ8vQEmVA0"],
  ["Oneohtrix Point Never - Again", "2zz6j2mGH5JHk0ihNvy6KM"],
  ["Nathan Fake - Crystal Vision", "3CL1XvaBaoVyMWpBUfnWtj"],
  ["Foo Fighters - But Here We Are", "4wp4aWWpoYfNcspimVAnel"],
  ["Hanakiv - Goodbyes", "5En0oSbOCytMKIlTKa8UUE"],
  ["Penguin Cafe - Rain Before Seven...", "4gGmqjw64211B9R3p2ikne"],
  ["Kali Uchis - Red Moon In Venus", "5OZ44LaqZbpP3m9B3oT8br"],
  ["Mort Garson - Journey To The Moon And Beyond", "6xaioaJ2ndCnEK8Zz5uOD7"],
  ["George Clanton - Ooh Rap I Ya", "2kvz9frUn3LUK83imD2BQS"],
  ["Wilco - Cousin", "1KZy1Oll0Cnnakyy6X92Wn"],
  ["Euglossine - Bug Planet Is The Current Timeline", "177o5J2HA5YBotifiOZrin"],
  ["Khotin - Release Spirit", "3Grw8AYCWpxN7RpOvrtxjF"],
  ["John Carroll Kirby - Blowout", "1PtMyRufUsbQ81yMxXjSym"],
  ["Anthony Naples - orbs", "2diDpno1K39g7HtGkPWiTe"],
];

const aotys2022: Aoty[] = [
  ["Alvvays - Blue Rev", "1dShPPoxXfzbjFO1jIHJZz"],
  ["Spiritualized - Everything Was Beautiful", "4s7idL3BJEZIpsytOCEPZK"],
  ["Cass McCombs - Heartmind", "2HutgntzLdadMPeSLrwmT1"],
  ["Jackie Cohen - Pratfall", "3KiQ2TSUc6N1ErcbZtT0Q0"],
  ["Nilufer Yanya - PAINLESS", "0iJ6CtgpIqzT1lYEqUu601"],
  ["Fresh Pepper - Fresh Pepper", "1BmPySRZiHQG7Hlw0flMc6"],
  ["Black Midi - Hellfire", "68z6MWYYNmvTcru1QMcYId"],
  ["Alex G - God Save The Animals", "6TzgWk5HZItbFmMT7hH4bU"],
  ["Sudan Archives - Natural Brown Prom Queen", "1QSo9HgowUqAc5BI3AdkqN"],
  ["Black Country, New Road - Ants From Up There", "21xp7NdU1ajmO1CX0w2Egd"],
  ["Weyes Blood - And In The Darkness, Hearts Aglow", "1hngVRZt95TrqPqXoJzQ4A"],
  ["Hudson Mohawke - Cry Sugar", "5J2NqsDqtVGCqb0bqQf3RU"],
  ["Denzel Curry - Melt My Eyez See Your Future", "7KtyUeiJidoZO0ybxBXw0Q"],
  ["Destroyer - Labyrinthitis", "63bs2cLZO9wm6hvhovU1AU"],
  ["Hurray For The Riff Raff - Life on Earth", "5oHaiGt9cgATxsrv409jP3"],
  ["Natalia Lafourcade - De Todas Las Flores", "4BJoDX0fIjR4RsFF4vyd81"],
  ["Beach House - Once Twice Melody", "79NySyjxJ8xric31mXKMAo"],
  ["Max Richter - The New Four Seasons", "6J7CIQ4ReSZa611kZjCRkb"],
  ["Mari Samuelsen - LYS", "3LHe1BsZZVZ5m7Mw4FxxPy"],
  ["FKA twigs - CAPRISONGS", "3G77BQuJy3jahjdkKQNNNM"],
  ["Kilo Kish - American Gurl", "5LXmSrGzPSEmTEu3OIsotT"],
  ["Maya Hawke - MOSS", "53RbAh13qFqN6wKraRLipl"],
  ["Jasmine Myra - Horizons", "0f3k4tF3PXSsRKnklbiKKe"],
  ["Horse Lords - Comradely Objects", "77I9CjThngVCVpPtvC67yp"],
  ["Szun Waves - Earth Patterns", "3AUaf40skBQVVJtBCJ13Bi"],
  ["Gold Panda - The Work", "3HfmS1eNJ3vFscFrdNauiK"],
  ["The 1975 - Being Funny In A Foreign Language", "6dVCpQ7oGJD1oYs2fv1t5M"],
  [
    "Big Theif - Dragon New Warm Mountain I Believe In You",
    "7Ln81p86r5cCsesd3KBWIY",
  ],
  ["The Smile - A Light For Attracting Attention", "009EjjwUjtdjvH7UP0wHzi"],
  ["Carlos Nino and Friends - Extra Presence", "21mdtatIUbfk3e9khF4bbG"],
  ["The Beths - Expert In A Dying Field", "1nAQg0AjzpuT7lINu1J87y"],
  ["beabadoobee - Beatopia", "2rhNQbqRNxiNQkDXTffe1V"],
  ["Jerry Paper - Free Time", "4iEmSaQR9Kz4SVs4O1wr1z"],
  ["DOMi & JD BECK - NOT TiGHT", "6cXQ0dxd2pWCTFhZ8RIg2j"],
  ["Florence + The Machine - Dance Fever", "4ohh1zQ4yybSK9FS7LLyDE"],
  ["James Krivchenia - Blood Karaoke", "30c7SBRELLApIDWDDkrBko"],
  ["Dry Cleaning - Stump Work", "64OXKq9VK1geZd3Q9OpoBO"],
  ["Wilco - Cruel Country", "5prfZewHLWnEMaWdDdgEb5"],
  ["Julia Jacklin - PRE PLEASURE", "5PtvMQZ7Wy4IsoXTszkH8B"],
  ["Kevin Morby - This Is A Photograph", "6NMzokKOYpPO9VXDjmc5y6"],
  [
    "King Gizzard & The Lizard Wizard - Laminated Denim",
    "5f0IPVaiRNK0knLx8UbqIq",
  ],
  ["Nueen - Diagrams of Thought", "6chSWHvbD3GenUJKtBgaDq"],
  ["Stella Donnelly - Flood", "3un2FDbZwuK5JidL4OFaTW"],
  [
    "Kaitlyn Aurelia Smith - I Could Be Your Dog / I Could Be Your Moon",
    "0Mh4KBhAf7Rvq2kHCu61YK",
  ],
  ["Danger Mouse - Cheat Codes", "4TPi1tGDVXCdQOjn4NSRaB"],
  ["Jockstrap - I Love You Jennifer B", "4YFlC5Abaj48ERwaOPfpu8"],
  ["Picnic - Creaky Little Branch", "11iWtMr4DGda1ABo20qlHA"],
  ["Animal Collective - Time Skiffs", "6GfYRMD52msi3dHjnGpOWv"],
  ["Vince Staples - RAMONA PARK BROKE MY HEART", "2G549zeda2XNICgLmU0pNW"],
  ["Carmen Villain - Only Love From Now On", "51gBdOcPhuUMKlSTO5CySL"],
];

const aotys2021: Aoty[] = [
  ["Porter Robinson - Nurture", "4Hjqdhj5rh816i1dfcUEaM"],
  ["Magdalena Bay - Mercurial World", "1ERrUvG31thFCxdwWUoJrY"],
  ["The War On Drugs - I Don't Live Here Anymore", "69jQsPvJzMvcb2fGqI2qaB"],
  ["JPEGMAFIA - LP!", "4inXqcdjG79gV4m2mU8dQh"],
  [
    "Cassandra Jenkins - An Overview On Phenomenal Nature",
    "1NzOdSkSNmBhhg72KlNcsE",
  ],
  ["Pond - 9", "3flX72PpF0OuV53f5HrKoS"],
  ["Jungle - Loving In Stereo", "3xuvOKpNqynROqZt8Tvcfh"],
  ["Godspeed You! Black Emperor - AT STATE'S END!", "6gZsJeN8MdITXZMVDXrMk0"],
  ["BADBADNOTGOOD - Talk Memory", "594yqwr1MOvVX0UBnOWftY"],
  ["Kanye West - Donda", "5CnpZV3q5BcESefcB3WJmz"],
  ["Low - HEY WHAT", "6S6jg2LuEwGdo9iYMSwCBS"],
  ["Wolf Alice - Blue Weekend", "1zt521PK0lam6J79DNMIJi"],
  ["Little Simz - Sometimes I Might Be Introvert", "4nOym5RKE8Opauf3rMxPAW"],
  ["L'Rain - Fatigue", "1L9yCNvMeREkOXyLPzxP0b"],
  ["St. Vincent - Daddy's Home", "654KFpNOZ26Hj9luu7aKeM"],
  ["DARKSIDE - Spiral", "09JglS9OxbpOkj5LXBsxYN"],
  ["CHVRCHES - Screen Violence", "0QVGIcTbPFeiArrgwRKKtG"],
  ["Floating Points - Promises", "3ShtO5VCYa3ctlR5uzLWBa"],
  ["Portico Quartet - Terrain", "5rCjfRxrqbeQYqMPzcn6M4"],
  ["Giant Claw - Mirror Guide", "7pyzhrIqI26oUxVurJ0WnH"],
  [
    "Bleachers - Take The Sadness Out Of Saturday Night",
    "6SPUtbeCQiPGej0t5RBasE",
  ],
  ["Clara Luciani - Coeur", "690kSW79qcdrg4cN03cBbC"],
  ["Wild Up - Julius Eastman, Vol. 1: Femenine", "1ld3DxwlntRQIplsQci5x2"],
  ["Grouper - Shade", "1w3EOCPDwqWIiu2c1pHylJ"],
  ["Leon Vynehall - Rare, Forever", "5UfCxNbc7RTtM6FyVqyi5x"],
  ["Koreless - Agor", "2mFlkozkxXwCdQgztSucRz"],
  [
    "Sam Wilkes - One Theme & Subsequent Improvisation",
    "4R5Y7xokLrEbn8G9LtdcHc",
  ],
  ["Asa Tone - New Forms", "7M6LLfu7XV5EfX3xoxWyQj"],
  ["Silk Sonic - An Evening With Silk Sonic", "4VZ7jhV0wHpoNPCB7Vmiml"],
  ["Foam and Sand - Full Circle", "6gk3iwAWUaGJXZtLqbjpQI"],
  ["Nueen - Circular Sequence", "3QHq0fdsTeYfqNbpfpdpYE"],
  ["Various Artists - @0", "0lzZgKs9XvoMHjPpBLWYA3"],
  ["Japanese Breakfast - Jubilee", "1uD1kdwTWH1DZQZqGKz6rY"],
  ["Xiu Xiu - OH NO", "4DcSlKtxqHwu4oXgdoUtGY"],
  ["black midi - Cavalcade", "7AsC27VDa3yOksZrfBSD6D"],
  ["The Weather Station - Ignorance", "3KeR5BDM2giFr8zoSXBrgE"],
  ["SPELLLING - The Turning Wheel", "5Dqqrr1dhaZ3BcFthVUCj2"],
  ["The Killers - Pressure Machine", "1qMFjBarjO2xD15BwXZguD"],
  ["Injury Reserve - By The Time I Get To Phoenix", "7L7oMPboBCeyGLJVsHSWM2"],
  ["Jon Hopkins - Music For Psychedelic Therapy", "2zY5p176SfmupXceLKT6bH"],
  [
    "Big Red Machine - How Long Do You Think It's Gonna Last?",
    "3YbMxdapL6mvSQjosFkc0T",
  ],
  ["Turnstile - GLOW ON", "2NrYPcMmQBlbBxopc2XlzS"],
  ["Remi Wolf - Juno", "7tJ8Wtej161vR0uCbGDiDR"],
  ["Adele - 30", "21jF5jlMtzo94wbxmJ18aa"],
  [
    "Carlos Nino & Friends - More Energy Fields, Current",
    "0IDpPQsBa9GpQGMHk6TJ4h",
  ],
  ["Dora Jar - Digital Meadow", "1Hs5SAioUMz5JA1qw8zrmZ"],
  ["Clairo - Sling", "32ium7Cxb1Xwp2MLzH2459"],
  ["Lorde - Solar Power", "4SBl4zvNIL4H137YRf2P0J"],
  ["Lana Del Rey - Chemtrails Over The Country Club", "6QeosPQpJckkW0Obir5RT8"],
  ["Arlo Parks - Collapsed In Sunbeams", "42joEEymK7EIHODfNB4yug"],
];

const aotys2020: Aoty[] = [
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
  ["", ""],
];

export const AOTYS: AotyList[] = [
  ["2023", aotys2023],
  ["2022", aotys2022],
  ["2021", aotys2021],
];
