const soty2023 = [
  ["Jungle - Back On 74", "19kHhX6f6EfLU7rcO3RqjO"],
  ["Skrillex - Rumble", "1GfBLbAhZUWdseuDqhocmn"],
  ["Taylor Swift - Now That We Don't Talk", "5KD6AEm19QnMbfWpfoOHMl"],
  ["Kieran Hebden - Darkness, Darkness", "2ih7916Ch16x9n75yhc3Ok"],
  ["Wild Nothing - Dial Tone", "5kgB80lRDpVcgl5a7BiGRr"],
  ["billy woods, Kenny Segal - Hangman", "4KDKMWbMBFJvfr5fEqYx0T"],
  ["Tinashe - Treason", "0HVcgx0BfhS5cjLrFl3Tmc"],
  ["Kali Uchis, Summer Walker - Deserve Me", "0vQffWKfl0JyRqtdoZINEM"],
  ["L'Rain - 5 to 8 Hours a Day (WWwaG)", "1YNkNFC58cqKfp65duBZbw"],
  ["Bombay Bicycle Club - Turn The World On", "2pkVFnJrUixqjhjf3In0G0"],
  ["Fever Ray - Even It Out", "4RgfngxUX05xp09dNutO1O"],
  ["Joanna Sternberg - Stockholm Syndrome", "0xmYbQpWsaVfk4Bn0up3Ej"],
  ["yeule - sulky baby", "2Euwbryh21DOB5zEH0WT4P"],
  ["George Clanton - I Been Young", "1gRDj5L77TVphFS2AT0nh3"],
  ["M83 - Amnesia", "3yARL62FmZMcL1LyReKqKX"],
  ["Sofia Kourtesis - Madres", "3oZOhcGFBx5AdxDmpp209k"],
  ["Avalon Emerson - Sandrail Silhouette", "23nECiREEvEMBDRZGodIks"],
  ["Mitski - My Love Mine All Mine", "3vkCueOmm7xQDoJ17W1Pm3"],
  ["Monsieur Perine - Onda Sensual", "64SoCFHUJPtLWM74RzNgc8"],
  ["Kara Jackson - no fun/party", "1HoSyT8MIKRUZ3q3ohEFiK"],
  ["Angel Olsen - Time Bandits", "5cZ0q2VQzkP0DRuNeyJzB4"],
  ["Beyonce - MY HOUSE", "7omJfT9s6V2IpQNBYyq5C8"],
  ["Zach Bryan - Oklahoman Son", "4ueTr01dkL360w1knfh21C"],
  ["Squid - Siphon Song", "2DM6h7z0WbDneTOTCE65wI"],
  ["Brittany Howard - What Now", "1g8becOwXRFEkYukY94L99"],
  ["feeble little horse - Paces", "6RiF8SC99TQlhS1HkdM7sF"],
  ["Men I Trust - Ring of Past", "11sfRkHdvsop5DdHVmGpt1"],
  ["King Krule - Seaforth", "5pEUZtevfA5f7bFewCDh3c"],
  ["Toro y Moi - Sidelines", "4mMviz9DJKLPyfhxpQIBcW"],
  ["Lana Del Rey - Margaret", "1o82DwNisONAd2mu1RcGE6"],
  ["PJ Harvey - A Child's Question, August", "0aq5fsNpJPIpfTmMO0mgx4"],
  ["PinkPantheress - Capable of love", "52qxHBgcQGVV2JrMwPhYJl"],
  ["Indigo De Souza - Losing", "3wKJhzOc2BKE09uvfoSnHA"],
  ["Beach House - American Daughter", "7CL67glGCz5kZNBJLmkhfu"],
  ["Julia Holter - Sun Girl", "0sMgwHapnEjJ7ixPHuvE8m"],
  ["The Chemical Brothers - Goodbye", "5Eyhw61L8qs4bdc6G4cfW3"],
  ["boygenius - Not Strong Enough", "09DR0sHnQUhHOiSNttc1mv"],
  ["Sampha - Spirit 2.0", "57s2fT1A0hOxscqF2Jipd5"],
  ["Yo La Tengo - Miles Away", "0crUa9CCdhANfB7vUWVeJ5"],
  ["Julie Byrne - Moonless", "3lCSiBordGtNz6yeF9JZA6"],
  ["MGMT - Mother Nature", "3kC6EmjBbLcnv1aAsAEGPP"],
  ["Olivia Rodrigo - making the bed", "5CscrLqFBgPfZR8fGtikov"],
  ["Jess Williamson - Hunter", "3aDfvlypxuh57TOqr7v3V4"],
  ["Fennesz - Senzatempo", "17yUqjvSmvJpCtPU9o7tzU"],
  ["Black Country, New Road - Dancers", "3FfGhV9jcpjhNeagvzYGkq"],
  ["Sufjan Stevens - Will Anybody Ever Love Me?", "7IAx9OvToHkT8C4ZlX9hwe"],
  ["Lonnie Holley - Mount Meigs", "1RhooG8JVU7RqMrveL4ESq"],
  ["U.S. Girls - Tux (Your Body Fills Me Boo)", "0cCGlP0ciQgqsg095WoRI7"],
  ["Susanne Sundfor - alyosha", "0dlxANxWScBqy8qkOweDVR"],
  ["Caroline Polachek - Welcome To My Island", "2QeUnYtvlfQdfWxzF3b1ud"],
];

const soty2022 = [
  ["Monsieur Perine - Nada", "343ZCS0FprOuhGbUxmIbmj"],
  ["Paramore - 26", "2EcQY09CYgJ1qk6H1qZf8h"],
];

export const SOTYS = [
  ["2023", soty2023],
  ["2022", soty2022],
];
