import { Soty, SotyList } from "@/models/track";

const sotys2023: Soty[] = [
  ["Caroline Polachek - Welcome To My Island", "2QeUnYtvlfQdfWxzF3b1ud"],
  ["Susanne Sundfor - alyosha", "0dlxANxWScBqy8qkOweDVR"],
  ["U.S. Girls - Tux (Your Body Fills Me Boo)", "0cCGlP0ciQgqsg095WoRI7"],
  ["Lonnie Holley - Mount Meigs", "1RhooG8JVU7RqMrveL4ESq"],
  ["Sufjan Stevens - Will Anybody Ever Love Me?", "7IAx9OvToHkT8C4ZlX9hwe"],
  ["Black Country, New Road - Dancers", "3FfGhV9jcpjhNeagvzYGkq"],
  ["Fennesz - Senzatempo", "17yUqjvSmvJpCtPU9o7tzU"],
  ["Jess Williamson - Hunter", "3aDfvlypxuh57TOqr7v3V4"],
  ["Olivia Rodrigo - making the bed", "5CscrLqFBgPfZR8fGtikov"],
  ["MGMT - Mother Nature", "3kC6EmjBbLcnv1aAsAEGPP"],
  ["Jessie Ware - Hello Love", "40bgBzGrYBURVjiQ4itEkh"],
  ["Julie Byrne - Moonless", "3lCSiBordGtNz6yeF9JZA6"],
  ["Yo La Tengo - Miles Away", "0crUa9CCdhANfB7vUWVeJ5"],
  ["Sampha - Spirit 2.0", "57s2fT1A0hOxscqF2Jipd5"],
  ["boygenius - Not Strong Enough", "09DR0sHnQUhHOiSNttc1mv"],
  ["The Chemical Brothers - Goodbye", "5Eyhw61L8qs4bdc6G4cfW3"],
  ["Julia Holter - Sun Girl", "0sMgwHapnEjJ7ixPHuvE8m"],
  ["Beach House - American Daughter", "7CL67glGCz5kZNBJLmkhfu"],
  ["Indigo De Souza - Losing", "3wKJhzOc2BKE09uvfoSnHA"],
  ["PinkPantheress - Capable of love", "52qxHBgcQGVV2JrMwPhYJl"],
  ["PJ Harvey - A Child's Question, August", "0aq5fsNpJPIpfTmMO0mgx4"],
  ["Lana Del Rey - Margaret", "1o82DwNisONAd2mu1RcGE6"],
  ["Toro y Moi - Sidelines", "4mMviz9DJKLPyfhxpQIBcW"],
  ["King Krule - Seaforth", "5pEUZtevfA5f7bFewCDh3c"],
  ["Men I Trust - Ring of Past", "11sfRkHdvsop5DdHVmGpt1"],
  ["feeble little horse - Paces", "6RiF8SC99TQlhS1HkdM7sF"],
  ["Brittany Howard - What Now", "1g8becOwXRFEkYukY94L99"],
  ["Squid - Siphon Song", "2DM6h7z0WbDneTOTCE65wI"],
  ["Zach Bryan - Oklahoman Son", "4ueTr01dkL360w1knfh21C"],
  ["Beyonce - MY HOUSE", "7omJfT9s6V2IpQNBYyq5C8"],
  ["Angel Olsen - Time Bandits", "5cZ0q2VQzkP0DRuNeyJzB4"],
  ["Kara Jackson - no fun/party", "1HoSyT8MIKRUZ3q3ohEFiK"],
  ["Monsieur Perine - Onda Sensual", "64SoCFHUJPtLWM74RzNgc8"],
  ["Mitski - My Love Mine All Mine", "3vkCueOmm7xQDoJ17W1Pm3"],
  ["Avalon Emerson - Sandrail Silhouette", "23nECiREEvEMBDRZGodIks"],
  ["Sofia Kourtesis - Madres", "3oZOhcGFBx5AdxDmpp209k"],
  ["M83 - Amnesia", "3yARL62FmZMcL1LyReKqKX"],
  ["George Clanton - I Been Young", "1gRDj5L77TVphFS2AT0nh3"],
  ["yeule - sulky baby", "2Euwbryh21DOB5zEH0WT4P"],
  ["Joanna Sternberg - Stockholm Syndrome", "0xmYbQpWsaVfk4Bn0up3Ej"],
  ["Fever Ray - Even It Out", "4RgfngxUX05xp09dNutO1O"],
  ["Bombay Bicycle Club - Turn The World On", "2pkVFnJrUixqjhjf3In0G0"],
  ["L'Rain - 5 to 8 Hours a Day (WWwaG)", "1YNkNFC58cqKfp65duBZbw"],
  ["Kali Uchis, Summer Walker - Deserve Me", "0vQffWKfl0JyRqtdoZINEM"],
  ["Tinashe - Treason", "0HVcgx0BfhS5cjLrFl3Tmc"],
  ["billy woods, Kenny Segal - Hangman", "4KDKMWbMBFJvfr5fEqYx0T"],
  ["Wild Nothing - Dial Tone", "5kgB80lRDpVcgl5a7BiGRr"],
  ["Taylor Swift - Now That We Don't Talk", "5KD6AEm19QnMbfWpfoOHMl"],
  ["Skrillex - Rumble", "1GfBLbAhZUWdseuDqhocmn"],
  ["Jungle - Back On 74", "19kHhX6f6EfLU7rcO3RqjO"],
];

const sotys2022: Soty[] = [
  ["Spiritualized - I'm Coming Home Again", "1gimcpvrhg3wsCoqDJi7Tq"],
  ["Cass McCombs - Karaoke", "0wn0gGMT0Yt1AUvOu1emNF"],
  ["Alvvays - Easy On Your Own?", "42oq4KDYcBwAHpEkV3PuWc"],
  ["Wilco - Tired of Taking It Out On You", "5XmNHFjqibxTcWxTcnnzjM"],
  ["Weyes Blood - Grapevine", "5BwfV9vNhDfIysUTyuTbuQ"],
  ["Everything Everything - Jennifer", "12uzUi6WTiWYb7qwWSRs6g"],
  ["Taylor Swift - Would've, Could've, Should've", "0aV5uARAknQgYhBaK944FP"],
  ["Alex G - Runner", "5DRnssBoVo8e7uAQZkNT8O"],
  [
    "King Gizzard & The Lizard Wizzard - The Dripping Tap",
    "0o6rOggbaLEvtwUHNztuD2",
  ],
  ["The 1975 - Looking For Somebody (To Love)", "0eNfURq0r0oNSwFyw1VuVT"],
  ["Destroyer - Suffer", "4A4fTvTs2cO8MLF3VRgxmz"],
  ["Jackie Cohen - Some Days", "1dYpdUbd7hEAGCBdXmIuhW"],
  ["Monsieur Perine - Nada", "4ruyGzUmYFy0tanBBLCxHW"],
  ["Max Richter - Spring 1", "2B3o5ddgGObs1M0CGkdTr9"],
  ["Denzel Curry - Walkin", "1q8DwZtQen5fvyB7cKbShC"],
  ["Hurray For The Riff Raff - RHODODENDRON", "3Ugq8kEET6KgKBmZ3ttCNl"],
  ["Florence + The Machine - Free", "7H7SHw3YWXhb4zYqyoPNa1"],
  ["Jockstrap - Glasgow", "2JTXw66YfzTRqFtWfdWkMV"],
  ["Julia Jacklin - End of a Friendship", "5aleXoeQxiA4XDeQsVIYBK"],
  ["M.I.A. - Marigold", "0T9sqokGD9XvJ8QJ0K1RkD"],
  ["Awe Kid - Eve (Max Cooper Remix)", "0nsHI6fq8ARRD2sKb21gjl"],
  ["Sofia Kourtesis - Estacion Esperanza", "1jGkLUJCl46NmXIM6rUghn"],
  ["Ibibio Sound Machine - Protection From Evil", "4JCTEAdqSG8GskU2k59K9O"],
  ["Danger Mouse - Aquamarine", "1WS1Q9G8vj0gPN2aOkZ80A"],
  ["Beth Orton - Friday Night", "1ETl1FlO7G2svRBUYiGEEH"],
  ["Nilufer Yanya - stabilise", "5UaQwesv5l438o4hp66JdR"],
  ["Fresh Pepper - Seahorse Tranquilizer", "6Wsm9HgQEyFs6BR8ABa7eA"],
  ["The Smile - Free In The Knowledge", "0p8esvsm33EFp9iABb8wH9"],
  ["Gang of Youths - the kingdom is within you", "7wGJdn5I6RVZ6eOJi4D7aI"],
  ["black midi - Still", "1WTYHbDGKGNE7ujGhXj5sD"],
  ["Szun Waves - New Universe", "1UNviAQZI2IlC7rKotOOKJ"],
  ["1969 Collective - Deux coeurs vagabonds", "5ASI75nECQm7rXWrPZSkbo"],
  ["Wet Leg - Chaise Longue", "0nys6GusuHnjSYLW0PYYb7"],
  ["Harry Styles - As It Was", "4Dvkj6JhhA12EX05fT7y2e"],
  ["Sudan Archives - Home Maker", "5vGZX134ZZktjCEYoDm462"],
  ["beabadoobee - See you Soon", "4Gy8ZglxsvsIX04R5PWY7U"],
  ["Kevin Morby - A Random Act of Kindness", "5GepgBdAV6eI3RoijuHZua"],
  ["The Beths - Knees Deep", "6QZ5TAWM48V8b6pkwByX5k"],
  ["hemlocke springs - girlfriend", "3oxjdkrul9fGW82LfkCdxg"],
  ["Jerry Paper - Duumb", "6cnmSKm9C6f29O6xyoEAgy"],
  ["Rachel Chinouriri - All I Ever Asked", "2F9DCIJ7ZXHhNkiIlIIOkw"],
  ["Angel Olsen - Right Now", "6R7HXdGChalsGEvAI4iSu0"],
  ["Dehd - Bad Love", "0atclF6Pp5MffEEi7CSFlE"],
  ["Pom Poko - Enduro Corner", "0YW6b1WksEH0A1xGVYePJp"],
  ["Stella Donnelly - Cold", "0VAkYFfY6PLyEGFpq7ie6P"],
  ["Charlotte Adigery & Bolis Pupul - It Hit Me", "6Z5NYVw0HnKtBTOoLbDSsl"],
  ["Phoebe Bridgers - Sidelines", "4SKvKJaqkRl1bUZWEqTYzl"],
  ["Charli XCX - Crash", "6WKDtdVILJvcfqpvSQgwAQ"],
  ["Sharon Van Etten - Porta", "6zfI5bLVFhDzYUBHmMA7ni"],
  ["Lous and The Yakuza - Kise", "29lLqXN6gPZv4Ol92YmkRn"],
];

const sotys2021: Soty[] = [
  ["St. Vincent - Somebody Like Me", "4AL1LM9QhlfRE7vwVsRbta"],
  ["Beach House - Superstar", "3w91918dPywkczARMO5tnJ"],
  ["The War On Drugs - Change", "3EPSnqfDkva43w9NdrfFmU"],
  ["Porter Robinson - Something Comforting", "6iZVQLI9gs9kFRnmbQLzHO"],
  ["Silk Sonic - Put On A Smile", "4bbJw6usZSqkcmnqjSIOWx"],
  ["DARKSIDE - The Limit", "5OBUmFuhkit7MYdaVZc2bs"],
  ["The Weather Station - Robber", "2cTLouneODFXlosSyN3sxK"],
  ["Magdalena Bay - You Lose!", "0abrcmbXF7sfC4Y5rnoLzP"],
  ["Jungle - Keep Moving", "6a88fc0zSrVWGPdoj445nJ"],
  ["Low - All Night", "5AjSHEwBGH6bPGN0arKmSb"],
  ["CHVRCHES - Final Girl", "2HO2We9xshtJANTe3S8052"],
  ["Japanese Breakfast - Be Sweet", "0dpyzcT3RMNNSd2xKBf35I"],
  ["Bleachers - Stop Making This Hurt", "7fRCD4vVNpCy91Y3zxNMUl"],
  ["The Killers - Pressure Machine", "74LIbDJcyc1g3EZ7pmDjF9"],
  ["Wolf Alice - Delicious Things", "6pAfAhSBOeNi5Tw8AfB5RQ"],
  ["Charli XCX - New Shapes", "2JvWoj5bTklsb6fPzRfZ3x"],
  ["Godspeed You! Black Emperor - Cliffs Gaze", "1IPDgRuF93WZzSsVVXdypb"],
  ["Little Simz - Introvert", "2lbX8Jt97ou14yL9rqG58C"],
  ["Men I Trust - Sugar", "6ZdAsADC9LIICvsVRuGWbZ"],
  ["Clark - Lambent Rag", "0s2X76Inz20xLRqOS2E8qW"],
  ["Clairo - Amoeba", "0HAqq2GcQKyi3s87GuN7jU"],
  ["Sharon Van Etten - Like I Used To", "1kZpYFQHUKv4xHELaaUSqP"],
  ["Pond - Pink Lunettes", "1NddmyhwlRYhZy6dZtC0lc"],
  ["Kanye West - Off The Grid", "6LNoArVBBVZzUTUiAX2aKO"],
  ["Big Red Machine - Phoenix", "5fwabfmJtYmNbcNd2ISl3x"],
  ["Giant Claw - Mirror Guide, Pt. I", "4rxk6CI2yx30cI4cLywsE0"],
  ["Koreless - Act(s)", "3v6cMjBPkOBaRZnMUM5yl8"],
  ["Lorde - Fallen Fruit", "5iUnomffoLeQsdlY2k5TDU"],
  ["Arlo Parks - Eugene", "4S6PolgPZ5OLph314ww8Fg"],
  ["SPELLLING - Turning Wheel", "5v6KYde3em7K9F6Lw9qMxn"],
  ["Xiu Xiu - A Bottle Of Rum", "7migEVdXZp1JzhqnvdG6eK"],
  ["Snail Mail - Valentine", "21brT2CZwKz8VPCf0nFxiP"],
  ["ABBA - I Still Have Faith In You", "3ddxe0WYUpNPtSnHgQOad5"],
  ["Clara Luciani - Amour toujours", "0Db6ejFxY0v2eIWVTNpf6J"],
  ["Injury Reserve - Knees", "7yZLz2CbWnpD8AKwCcMvgi"],
  ["JPEGMAFIA - KISSY, FACE EMOJI!", "5w4KWZatyMvra1cuekHTl3"],
  ["Cassandra Jenkins - Hard Drive", "3ArnNhm8z0ScjDKfGHSBRk"],
  ["BADBADNOTGOOD - Love Proceeding", "5F8XPD481L6K2s8h02Vxuo"],
  ["L'Rain - Find It", "2z2akz47l8Eeri9gmFx46d"],
  ["Portico Quartet - Terrain: I", "1eK10o5EYvOSIOnA4neki6"],
  ["Ross from Friends - The Daisy", "4QNMkhd49G4xJVQCrbrhst"],
  ["BICEP - Lido", "0HZtVLVL6oLU9WobKQxqGu"],
  ["Madlib - One For Quartabe / Right Now", "4sjMb1ZnDsUV1CZkbb6FGb"],
  ["Feu! Chatterton - Un Monde Nouveau", "4Zw1FnXHjeLdK67gERdKXr"],
  ["Nueen - Syn", "5Aao9k9ci6VxhaDXpXF3ib"],
  ["Daniel Pemberton - Behind the Eyes", "7oFocF6NHEyASI4A8y0aCS"],
  ["Carlos Nino & Friends - Nightswimming", "5gpsn14DqafMKNSH1NnPxE"],
  ["Asa Tone - II", "6oIY2G2GKeIx6cZKv75bZs"],
  ["Dora Jar - Wizard", "6q8bIgs9jfJpkM3bJmbDie"],
  ["Leon Vynehall - An Exhale", "1Cdi1HIK4bJD3F8HGKZDQQ"],
];

const sotys2020: Soty[] = [
  ["The Strokes - At The Door", "7lu6YLrlB1MU7HW8DJSuPa"],
  ["Fiona Apple - Ladies", "0jH0IsCBGackT3RmHBbSUI"],
  ["Jessie Ware - Spotlight", "0EtcGmf2mVZbHWq2ZGP3t7"],
  ["Perfume Genius - On The Floor", "4AoNwjnuCFD0uRgdJrReQO"],
  ["HAIM - Hallelujah", "2TOjLvePl2m3lzzhvAzdhS"],
  ["Rina Sawayama - Bad Friend", "1ApN1loxlt0rzRFc8iETw7"],
  ["The Killers - Dying Breed", "0SieiDcGvj8cZ0K4hcT3Zd"],
  ["Taylor Swift - august", "6nK2pIKFcRc5frrZKHgsiT"],
  ["Oneohtrix Point Never - Long Road Home", "6E3cE3vFN4pb4JN4R3kAaV"],
  ["Against All Logic - If Loving You Is Wrong", "5DksmF3xtwlI6TEPxOSRe8"],
  ["Laura Marling - Held Down", "2PHeCBCWESSAqfxpORbxKA"],
  ["Grimes - Delete Forever", "2MJYFjgD8qXBqtvSGvhF8a"],
  ["Phoebe Bridgers - Chinese Satellite", "1scaOnahzG7o8pfwfsL784"],
  ["Adrianne Lenker - not a lot, just forever", "11hEwcy9LMEvzAlOYAFhkK"],
  ["U.S. Girls - 4 American Dollars", "7MpAhr2TMxYU9cku7v8ZoR"],
  ["A.G. Cook - Silver", "7jckam3u2rKAPqwscTcBY1"],
  ["Nicolas Jaar - Telencima", "5EfIzDYQLlsVb5FmKCxRcF"],
  ["Charli XCX - c2.0", "5gNTRfMRPZg1U07j7KSSaG"],
  ["Fleet Foxes - Can I Believe You", "6CMl975c8awpTvZUkQo8ER"],
  ["The 1975 - Playing On My Mind", "2q3s94g1UFU90IinOiFmDQ"],
  ["Hannah Georgas - That Emotion", "6NZOSB922ynmdvniiKP3VX"],
  ["Moses Sumney - Bless Me", "4LXbKn68LvcWfBrHwEWqRH"],
  ["Tame Impala - Breathe Deeper", "3LbZIhU0smEU5SUnxod4j4"],
  ["The Weeknd - Hardest To Love", "6kWxIqQDsKFYCJGbU4AjCX"],
  ["Julianna Barwick - Safe", "6JM5pGkZn1GQQlG0KuuwbF"],
  ["Caribou - Ravi", "41LSmsKx5gXHFfFg9lhsA0"],
  ["K-Lone - Bluefin", "51zMZTMVRNRT1fxWjoW7Td"],
  [
    "Kaitlyn Aurelia Smith - The Spine Is Quiet In The Center",
    "2J2ZwrTby2o3QeVNSBv1l8",
  ],
  ["Khotin - Outside In The Light", "3Fa2iWHEl5nYvWYOygu2i5"],
  ["GODTET - Neon", "17khyaq6V0szZWEopFncBo"],
  ["Iceblink - Cellphone in the Bath", "7FQ2zIoPEBSZAxhNm63Pm4"],
  ["Kelly Moran - Sodalis", "5MVM7ZY4QWuKbWedQJ6ERr"],
  ["Four Tet - Insect Near Piha Beach", "2pOV1do0oBMOcEy4kT3ySp"],
  ["Pantha Du Prince - When We Talk", "3mMfLjab0kQ8z9xEUB97yK"],
  ["Sea Oleena - Will I Know", "4GxJ73wgwSry1gFXLSlk1r"],
  ["Beatrice Dillon - Workaround Eight", "27J1E34ijJP5i9OY9fZbNL"],
  ["Nathan Fake - Ezekiel", "23OzFoiQ575KUH7TYQ2SB1"],
  ["King Krule - Underclass", "3ASM8szSZoBVHoX4cKDNdY"],
  ["Destroyer - Cue Synthesizer", "10usKt8CPNW1kpYlDFRLbt"],
  ["Dan Deacon - Sat By A Tree", "7mXRbgPvpEgCtvs26cbOxc"],
  ["Thundercat - Dragonball Durag", "7eWGnKg4B44sbBPpQp4y2c"],
  ["Asa Tone - River At Work", "5wbJAYsmAKh51Z8K09ZiSx"],
  ["The Japanese House - Dionne", "15gL4n95OG5KEQLCMXPQzp"],
  [
    "Nonlocal Forecast - Extended To Disparate Fields",
    "0oRBXgK1CJL8UnSwrx3w2i",
  ],
  ["Max Cooper - Opening", "3dj1mKqrrSdeXl7GLo95Nn"],
  ["James Krivchenia - Idiot Passion", "5gbyqS09TWACrWt6tboJ51"],
  ["Kylie Minogue - Dance Floor Darling", "1tojfdDueOdEY0T98Mudx4"],
  ["Dua Lipa - Levitating", "1dI77VhaLcQSgQLSnIs03D"],
  ["Eyeliner - Los Angeles", "6KQI2wgkkFz4fjNxvdhHEt"],
  ["Daniel Avery - Enter Exit", "7wuuqyvG8y72HPxoFIa2oc"],
];

export const SOTYS: SotyList[] = [
  ["2023", sotys2023],
  ["2022", sotys2022],
  ["2021", sotys2021],
  ["2020", sotys2020],
];
